### PR TITLE
Include tests in PyPI tarball

### PR DESCRIPTION
**Pull request by dotlambda**

### CODE REVIEW

**Comment by alanhamlett** [comment]
No, we shouldn't include tests in releases.

**Comment by dotlambda** [comment]
Some of the big names are doing it: Numpy, Cython, ...
I think it makes sense because e.g. distributions might want to include a test phase in their build instructions, just to make sure the package works fine with the packaged versions of all of its dependencies.

**Comment by alanhamlett** [comment]
There are ways around that without having to include tests in releases.

Also, if a release fails to build on a specific environment then a test should be written that correctly mocks that environment and that test should fail in automated/dev environments. That way problems are caught before they reach a release.

There's always a better alternative rather than including unit tests or other dev-only code in releases.

**Comment by sh4nks** [comment]
> Also, if a release fails to build on a specific environment then a test should be written that correctly mocks that environment and that test should fail in automated/dev environments. That way problems are caught before they reach a release.

Yep, I agree.

@dotlambda Thanks for your PR nevertheless!

**Pull request closed without merging**
