### PR TITLE
Add type annotations

### PR DESCRIPTION
**Pull request by MartinThoma**
See issue #197

### CODE REVIEW

**Comment by sh4nks** [comment]
Sorry for getting back to your PR so late. Looks good, however there appears to a conflict with current master. Could you rebase you PR against the latest master?

**Comment by MartinThoma** [comment]
@sh4nks No problem; I've rebased and pushed again :-)

**Comment by MartinThoma** [comment]
I've also added the [`Typing :: Typed`](https://pypi.org/search/?c=Typing+%3A%3A+Typed) trove classifier

**Comment by sh4nks** [comment]
Thanks!

**Comment by hnicholson-Ocient** [comment]
@MartinThoma do these changes work for mypy? I have started using mypy in my project which is using v1.10.1 of this package, which includes these changes. mypy complains with
```
cache.py:3: error: Skipping analyzing 'flask_caching': found module but no type hints or library stubs
```

Based on the [mypy docs,](https://mypy.readthedocs.io/en/latest/running_mypy.html#fix-missing-imports) packages need to both have types, and declare themselves to be pep 561 compliant (or registered themselves on [typeshed](https://github.com/python/typeshed) ).

I can create an issue for this, I just wanted to check if you had this working in mypy for you.

**Pull request merged**
