### PR TITLE
Added support for caching functions under properties

### PR DESCRIPTION
**Pull request by sallyruthstruik**
See https://github.com/sh4nks/flask-caching/issues/16

### CODE REVIEW

**Comment by sh4nks** [comment]
Thanks for this PR.

I would appreciate if you could move the tests to the ``test_cache.py`` file for consistency's sake.

Sorry that it took so long.

**Comment by sallyruthstruik** [comment]
Sorry for long reply, 

I've done your requests.  I'm not sure  I've put changes in correct version block, so if I'm wrong please tell me.

**Comment by sh4nks** [comment]
After giving it some thoughts I decided that I'm not merging this. At the moment you just cache the result of a method and return it in a property:
```python
class Foo(object):

    #  ...

    @property
    def foobar(self):
        return self.get_foobar()

    @cache.memoize()
    def get_foobar(self):
        pass
```
If there is demand for this functionality I might reconsider this feature.

**Comment by huangxiaohen2738** [comment]
Ungraced

**Comment by indiquant** [comment]
Hi @sh4nks , I was looking online for a solution like this and I stumbled upon this PR. There is certainly a need for this feature. I would greatly appreciate if you could open this PR for merge.

Cc. @sallyruthstruik

**Comment by bw984** [comment]
I agree with @indiquant that there are use cases where excluding parameters from the key would be very useful.

**Pull request closed without merging**
