### PR TITLE
WIP: Redis sentinel support

### PR DESCRIPTION
**Pull request by gergelypolonkai**
Documented solution for #40 

This is basically the original commit of @sh4nks (rebased onto the current master) with some documentation added. It still needs some testing and possibly some additions, but it seems to be a good start.

### CODE REVIEW

**Comment by gergelypolonkai** [comment]
While live testing this, i found there are a lot of things missing; for example there is no way to authenticate with the sentinel instances. I’ll add this soon to this PR.

**Comment by sh4nks** [comment]
This is looking good already! Let me know when it's ready to be merged.

**Comment by gergelypolonkai** [comment]
It would be awesome if someone could give it a go (other than me, i mean). Other than that, it’s pretty much done except some tests maybe.

**Comment by sh4nks** [comment]
I'll try it out as I do have some spare time this afternoon :)

However, I am not exactly sure how to set up Redis-Sentinel - any tips?

**Comment by gergelypolonkai** [comment]
Last time i used [this](https://seanmcgary.com/posts/how-to-build-a-fault-tolerant-redis-cluster-with-sentinel/) article to do it. For testing purposes it’s enough to set up one sentinel with two slaves. If you want to go for 100% (ie. production), you might need at least three sentinels, though.

**Comment by sh4nks** [comment]
I do have some fixes for your PR. Either you apply them or you could also set the PR to allow commits from the maintainers (https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by gergelypolonkai** [comment]
The allow maintainers to edit checkbox is ticked, so i guess you should be able to add commits.

I think the refactoring/import reorganising related stuff should be separate from this PR, but that might be just my OCD speaking :)

The `BaseCache.__init__()` call might be justified, as `RedisCache.__init__()` does things we don’t want `RedisSentinelCache.__init__()` to do. Namely checking the `host` argument, which is not passed to `RedisSentinelCache` at all (it needs `sentinel_hosts` instead). The current soluotion, however, makes PyLint to yell at me for not calling the constructor of the parent class, and that makes me feel uncomfortable. But unless we want to completely duplicate the methods of `RedisCache`, we might instead create a `RedisCacheBase` class that might be the copy of the current `RedisCache` without `__init__`, then recreate `RedisCache` with its current `__init__`, and keep the `RedisSentinelCache` as is (with the new base class). Another option might be to completely ditch `RedisSentinelCache` and modify `RedisCache` so it can connect to a sentinel setup. That, however, might be slightly harder work.

You renaming `self._read_clients` to `self._read_client` is valid from a grammatic PoV, but might be wrong otherwise. While `_write_client` will always be one specific client (as told by the sentinels), `_read_client` is a connection pool with one or more slaves. I’m still OK with renaming it, though, i’m just saying :)

**Comment by sh4nks** [comment]
> The `BaseCache.__init__()` call might be justified, as `RedisCache.__init__()` does things we don’t want `RedisSentinelCache.__init__()` to do.

But it does not work with having `BaseCache.__init__()`. I did the tests using the example app in `examples/`.

Ok, then lets just exclude the last patch ([PATCH 3/3] Use super()-style for initializing inherited parent) from this PR.

My bad, I actually just wanted to pass the same arguments as were passed before.

> You renaming `self._read_clients` to `self._read_client` is valid from a grammatic PoV, but might be wrong otherwise. While `_write_client` will always be one specific client (as told by the sentinels), `_read_client` is a connection pool with one or more slaves. I’m still OK with renaming it, though, i’m just saying :)

I was just doing the fastest way of fixing the things - because in RedisCache, everywhere `self._read_client` is used instead of `self._read_clients`.

**Comment by gergelypolonkai** [comment]
Oh, i take a day out and you merged it already? 😃 Thanks a lot!

Do you think you will release it any time soon?

**Comment by sh4nks** [comment]
Yeah I'll push out a new release soon. I still have a couple of changes in the pipeline that I would like to have in the release.

**Pull request merged**
