### PR TITLE
Change redis import mechanism to avoid ignoring ImportErrors

### PR DESCRIPTION
**Pull request by jkgeyti**
In response to https://github.com/sh4nks/flask-caching/issues/13

### CODE REVIEW

**Comment by sh4nks** [comment]
Looks good, the only thing I'd change is to move the RedisCache import to the top of the file (where the other Cache classes are imported. I think it's safe to remove support for version < 0.7 of werkzeug.

Maybe wrap the import in a try-except and raise a exception if redis can't be imported (I have been inspired from [here](https://github.com/pallets/werkzeug/blob/master/werkzeug/contrib/cache.py#L555-L558))

```python
def redis(...):
    try:
        import redis
    except ImportError:
        raise RuntimeError('no redis module found')
```

**Comment by jkgeyti** [comment]
Done. You may also want to consider moving `backends` into its own module, so you can better control what's being exposed through an `__init__.py`.

**Comment by sh4nks** [comment]
Thanks, I really appreciate it! That's actually a neat idea. Do you want to do that?

**Comment by jkgeyti** [comment]
Sure. I've moved backends to a separate folder and added an init file. It's untested, so you might want to take a close look at whether you agree with the solution. You might want to use `__all__` instead.

**Comment by sh4nks** [comment]
Thanks! Looks like adding a ``__all__`` in ``backends.py`` is the way to go and then use ``from .backends import *`` in ``__init__.py``. I'll just add that and release a new version.

**Comment by sh4nks** [comment]
The new version should be on PyPI now :)

**Comment by johaven** [comment]
On last version (1.7.2) no warning is fired if redis module cannot be imported (or missing)

**Pull request merged**
