### PR TITLE
try catch on memoize() to match cached()

### PR DESCRIPTION
**Pull request by justinwp**
Might as well have the same behavior for both cached() and memoized().

### CODE REVIEW

**Comment by sh4nks** [comment]
I'd prefer it the other way around - adjusting the ``memoize()`` method to match ``cached()``.

**Comment by justinwp** [comment]
that is what this change does, modify `memoize()` to match `cached()`

**Comment by sh4nks** [comment]
Ah sorry.. i mixed it up - what I wanted to say is if you could modify ``cached()`` to match ``memoize()``.

**Comment by sh4nks** [comment]
Added with #60 but thanks anyway!

**Pull request closed without merging**
